version: '3'

services:
  tickets:
    build:
      context: ./tickets
      dockerfile: Dockerfile.test
    volumes:
      - ./tickets:/usr/src/app/tickets
      - /usr/src/app/tickets/node_modules
    ports:
      - '1337:1337'
    networks:
      - block-network
networks:
  block-network:
    driver: bridge
