version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.production
    restart: always # because it is routing traffic to our entire app
    ports:
      - 80:80
      - 443:443
    networks:
      - block-network
    volumes:
      - $PWD/nginx/certs:/etc/nginx/certs
      - $PWD/nginx/configs/production/upstream.conf:/etc/nginx/conf.d/upstream.conf
  tickets:
    build:
      context: ./tickets
      dockerfile: Dockerfile.production
    volumes:
      - ./tickets:/usr/src/app/tickets
      - /usr/src/app/tickets/node_modules
    ports:
      - '1337:1337'
    networks:
      - block-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    ports:
      - '3000:3000'
    networks:
      - block-network
networks:
  block-network:
    driver: bridge