version: '3'

services:
  tickets:
    build:
      context: ./tickets
      dockerfile: Dockerfile
    volumes:
      - ./tickets:/usr/src/app/tickets
      - /usr/src/app/tickets/node_modules
    ports:
      - '1337:1337'
    networks:
      - block-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    ports:
      - '3000:3000'
    networks:
      - block-network
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    volumes:
      - ./admin:/usr/src/app/admin
      - /usr/src/app/admin/node_modules
    ports:
      - '3001:3001'
    networks:
      - block-network
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - block-network
networks:
  block-network:
    driver: bridge
