# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  slack: circleci/slack@4.5.1

commands:
  trigger_slack_notification:
      steps:
        - slack/notify:
            custom: |
              {
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "plain_text",
                        "text": "Deploying new build to blocktickets I'll message again once complete",
                        "emoji": true
                      }
                    ]
                  }
                ]
              }
            event: always
  trigger_admin_slack_notification:
      steps:
        - slack/notify:
            custom: |
              {
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "plain_text",
                        "text": "Deploying new build to admin UI I'll message again once complete",
                        "emoji": true
                      }
                    ]
                  }
                ]
              }
            event: always
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  pull-and-build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: circleci/node:14
    steps:
      - trigger_slack_notification
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"
      - notify_slack_error
      - notify_slack_pass
  pull-and-build-admin:
    docker:
      - image: circleci/node:16
    steps:
      - trigger_admin_slack_notification
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$ADMIN_IP "./deploy.sh"
      - notify_slack_error
      - notify_slack_pass

# Orchestrate our job run sequence
workflows:
  version: 2
  build-deploy:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - preview
      - pull-and-build-admin:
          filters:
            branches:
              only:
                - preview
