# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM node:16 as build-stage

# set working directory

WORKDIR /app

COPY package.json ./
RUN npm config set legacy-peer-deps true
RUN npm install

# add app
COPY . .

RUN npm run build